### ISSUE TITLE
importing schems makes holes

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/preload#12]
![screenshot_20160408_032042](https://cloud.githubusercontent.com/assets/12679496/14379896/daf42542-fd39-11e5-9ca0-8d81aecdb546.png)

I don't remember this happening before. I have moved the importing code to after the other map_block writing, and even tried it after the save() but it still cuts into the existing map...

**Comment by LeMagnesium** [comment]
Did your schematic contain air?

**Comment by bobombolo** [comment]
yes i'm sure it does. I guess I am just asking if we can have options such as the minetest lua api method to force/not force replacement and/or "ignore" air (the lua api method doesn't have an ignore air, just the force option):

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2326

i may be ignorant about making schematics but I don't see an easy way using the create_schem method in the lua API to ignore air: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2309 so I thought your python import_schem method could match the behavior of the lua api. it could even have the random rotation option...

i'm just inquiring / requesting these features, I will write the behavior into my own script or make better schems if it is not something that should be added...  =)

**Comment by LeMagnesium** [comment]
>  I guess I am just asking if we can have options such as the minetest lua api method to force/not force replacement and/or "ignore" air (the lua api method doesn't have an ignore air, just the force option)

That's exactly what I was planning to code after I read your issue's title.

> I thought your python import_schem method could match the behavior of the lua api.

Well I'm not forced to. In fact I will probably not act as the API does. I plan on using an keyword called "ignore" which contains a table of node name to ignore when importing and exporting.

> it could even have the random rotation option...

I guess this is related to param1 or param2 or the nodes... maybe... When I find enough documentation about it, or read the code..

**Comment by bobombolo** [comment]
ignore air fixes this well enough to use
