### ISSUE TITLE
mixing preload and lua mapgen

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/preload#14]
the loaded blocks do not seem to count as being "generated". when you preload a dem and then activate the realterrain mod and use the same dem the blocks that have been preloaded get overwritten by on_generated() which is good in a way because the trees and underground get generated properly but it would be nice to know how to mark a block as being generated during preload because that is the expected behavior.

**Comment by bobombolo** [comment]
it might be a blessing that this is the case because of the lighting issue...
https://github.com/LeMagnesium/python-minetest/issues/13

anyway I am doing some preliminary tinkering with this and it has led to solving a few other outstanding issues. however there is a misalignment issue, the preload code places nodes one node too far to the south:
![screenshot_20160420_124234](https://cloud.githubusercontent.com/assets/12679496/14690288/4d984176-0700-11e6-86bc-2d85fd54f4a2.png)

**Comment by bobombolo** [comment]
this branch of realterrain now has the preload.py and they share config files...
https://github.com/bobombolo/realterrain/tree/python

**Comment by Tank-ACiD** [comment]
nice will check it out

**Comment by bobombolo** [comment]
i think this alignment issue has been fixed
